name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '10 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v4.1.0
      with:
        # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
        stale-issue-message: "Marking as stale due to 30 days of inactivity." # optional
        # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
        stale-pr-message: "Marking as stale due to 30 days of inactivity." # optional
        # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
        close-issue-message: "Closing as stale due to 60 days of inactivity." # optional
        # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
        close-pr-message: "Closing as stale due to 60 days of inactivity." # optional
        # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
        days-before-stale: 30 # optional, default is 60
        # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
        days-before-close: 30 # optional, default is 7
        # The label to apply when an issue is stale.
        stale-issue-label: "stale" # optional, default is Stale
        # The label to apply when an issue is closed.
        close-issue-label: "stale-closure" # optional
        # The labels that mean an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2").
        exempt-issue-labels: "example" # optional, default is 
        # The label to apply when a pull request is stale.
        stale-pr-label: "stale" # optional, default is Stale
        # The label to apply when a pull request is closed.
        close-pr-label: "stale-closure" # optional
        # The labels that mean a pull request is exempt from being marked as stale. Separate multiple labels with commas (eg. "label1,label2").
        exempt-pr-labels: "example" # optional, default is 
        # The milestones that mean an issue or a pull request is exempt from being marked as stale. Separate multiple milestones with commas (eg. "milestone1,milestone2").
        exempt-assignees: "Alexander-Maples" # optional, default is 
